name: CI Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint-and-format:
        name: Lint & Format Check
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v4
              
              
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.13

            - name: Install uv
              run: |
                curl -LsSf https://astral.sh/uv/install.sh | sh
                echo "${CARGO_HOME:-$HOME/.cargo}/bin" >> $GITHUB_PATH

            - name: Install dependencies
              run: |
                uv pip install --system ruff black

            - name: Run linting
              run: ruff check .

            - name: Run formatting
              run: black .
            
            
        