name: CI Pipeline

on:
    push:
        branches:
            - main
    pull_request:
        branches:
            - main

jobs:
    lint-and-format:
        name: Lint & Format Check
        runs-on: ubuntu-latest

        steps:
            - name: Check out repository
              uses: actions/checkout@v4
              
              
            - name: Set up Python
              uses: actions/setup-python@v4
              with:
                python-version: 3.13

            - name: Install uv
              run: |
                curl -fsSL https://get.uv.dev | sh
                echo "$HOME/.uv/bin" >> $GITHUB_PATH

            - name: Install dependencies
              run: |
                $HOME/.uv/bin/uv pip install --system ruff black
                $HOME/.uv/bin/uv sync

            - name: Run linting
              run: ruff check .

            - name: Run formatting
              run: black .
            
            
        